const config = {
  icons: {
    0: "bi-brightness-high-fill",
    1: "bi-cloud-sun-fill",
    2: "bi-cloud",
    3: "bi-cloud-fill",
    45: "bi-cloud-fog",
    48: "bi-cloud-fog2",
    51: "bi-cloud-drizzle",
    53: "bi-cloud-drizzle",
    55: "bi-cloud-drizzle",
    61: "bi-cloud-rain",
    63: "bi-cloud-rain-heavy",
    65: "bi-cloud-lightning-rain",
    71: "bi-snow",
    73: "bi-snow2",
    75: "bi-snow3",
    80: "bi-cloud-lightning",
    95: "bi-cloud-lightning-fill",
    200: "bi-cloud-lightning",
    300: "bi-cloud-drizzle",
    500: "bi-cloud-rain",
    600: "bi-snow",
    800: "bi-brightness-high-fill",
    801: "bi-cloud-sun",
    802: "bi-cloud",
    803: "bi-clouds",
    804: "bi-cloud-fill",
    200: "bi-cloud-lightning",
    201: "bi-cloud-lightning-rain",
    202: "bi-cloud-lightning-rain",
    210: "bi-cloud-lightning",
    211: "bi-cloud-lightning-fill",
    212: "bi-cloud-lightning-fill",
    221: "bi-cloud-lightning-fill",
    300: "bi-cloud-drizzle",
    301: "bi-cloud-drizzle-fill",
    302: "bi-cloud-drizzle-fill",
    500: "bi-cloud-rain",
    501: "bi-cloud-rain-heavy",
    502: "bi-cloud-rain-heavy-fill",
    503: "bi-cloud-rain-heavy-fill",
    504: "bi-cloud-rain-heavy-fill",
    600: "bi-snow",
    601: "bi-snow2",
    602: "bi-snow3",
    611: "bi-cloud-sleet",
    621: "bi-snow",
    701: "bi-cloud-fog",
    711: "bi-cloud-haze2",
    721: "bi-cloud-fog",
    731: "bi-cloud-hail",
    741: "bi-cloud-fog",
    751: "bi-cloud-hail",
    761: "bi-cloud-hail",
    762: "bi-cloud-hail",
    800: "bi-brightness-high-fill",
    801: "bi-cloud-sun",
    802: "bi-cloud",
    803: "bi-clouds",
    804: "bi-cloud-fill",
    900: "bi-tornado",
    901: "bi-cloud-hail",
    902: "bi-hurricane",
    903: "bi-thermometer-snow",
    904: "bi-thermometer-sun",
    905: "bi-wind",
    906: "bi-cloud-hail",
  },
  descriptions: {
    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    45: "Fog",
    48: "Rime fog",
    51: "Light drizzle",
    53: "Moderate drizzle",
    55: "Dense drizzle",
    61: "Slight rain",
    63: "Moderate rain",
    65: "Heavy rain",
    71: "Light snow",
    73: "Moderate snow",
    75: "Heavy snow",
    80: "Rain showers",
    95: "Thunderstorm",
  },
};
